### ISSUE TITLE
In centos 7 , npm start has an error.

### ISSUE THREAD

**Issue by leeeco610** [koahubjs/koahub-simple-cms#2]
[root@iZ9428j1umdZ koahub-simple-cms]# npm start

> koahub-simple-cms@2.0.0 start /home/lihaipeng/www/koahub-simple-cms
> node app.js

/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "env" relative to directory "/home/lihaipeng/www/koahub-simple-cms/app/config"
    at /home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/babel-core/6.24.0/babel-core/lib/transformation/pipeline.js:46:16)
    at compileByBabel (/home/lihaipeng/www/koahub-simple-cms/node_modules/.npminstall/koahub-cli/0.3.0/koahub-cli/lib/index.js:89:22)

npm ERR! Linux 3.10.0-327.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! koahub-simple-cms@2.0.0 start: `node app.js`
npm ERR! Exit status 1

**Comment by einsqing** [comment]
Can you run [koahub-demo](https://github.com/koahubjs/koahub-demo)?

**Comment by leeeco610** [comment]
koahub-demo is ok.

**Comment by einsqing** [comment]
Should not ah, you try again koahub-simple-cms

**Comment by leeeco610** [comment]
cnpm i  --> run error
npm i -->  run success
yarn  --> run success

**Comment by einsqing** [comment]
It's embarrassing, the estimate is cnpm bug

**Comment by leeeco610** [comment]
I think so.
